# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_add_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='categoria',
            field=models.CharField(choices=[('ssd', 'SSD / HD'), ('placa_video', 'Placa de Vídeo'), ('placa_mae', 'Placa-mãe'), ('processador', 'Processador'), ('memoria_ram', 'Memória RAM'), ('notebook', 'Notebook'), ('monitor', 'Monitor'), ('celular', 'Celular / Smartphone'), ('tv', 'TV'), ('headset', 'Fone / Headset'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('cadeira', 'Cadeira Gamer'), ('impressora', 'Impressora'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
    ]
