# Generated by Django 6.0.2 on 2026-03-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_add_placa_mae_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='cupom',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
