# Generated by Django 6.0.2 on 2026-03-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_increase_cupom_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='link_afiliado',
            field=models.CharField(max_length=2000),
        ),
    ]
