# Generated by Django 6.0.2 on 2026-08-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_refactor_link_afiliado_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='url_chave',
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
    ]
