# Generated by Django 6.0.2 on 2026-08-06 17:04

from django.db import migrations, models
from bot.classifier import detectar_loja


def preencher_lojas(apps, schema_editor):
    Promo = apps.get_model('bot', 'Promo')
    for promo in Promo.objects.filter(loja='').iterator():
        loja = detectar_loja(promo.link_afiliado)
        if loja:
            promo.loja = loja
            promo.save(update_fields=['loja'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_promo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='loja',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.RunPython(preencher_lojas, noop),
    ]
