# Generated by Django 5.0.1 on 2026-08-07 01:18

from django.db import migrations, models
from bot.classifier import detectar_categoria
from bot.services import _linha_titulo


def reclassificar_promos(apps, schema_editor):
    Promo = apps.get_model('bot', 'Promo')
    for promo in Promo.objects.all().iterator():
        titulo = _linha_titulo(promo.texto_original or promo.titulo)
        nova = detectar_categoria(promo.texto_original or promo.titulo, titulo=titulo)
        if nova and nova != promo.categoria:
            promo.categoria = nova
            promo.save(update_fields=['categoria'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_promo_mousepad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='categoria',
            field=models.CharField(choices=[('ssd', 'SSD / HD'), ('placa_video', 'Placa de Vídeo'), ('placa_mae', 'Placa-mãe'), ('processador', 'Processador'), ('memoria_ram', 'Memória RAM'), ('kit', 'Kit (Placa + CPU + RAM)'), ('notebook', 'Notebook'), ('monitor', 'Monitor'), ('celular', 'Celular / Smartphone'), ('tv', 'TV'), ('headset', 'Fone / Headset'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('mousepad', 'Mousepad'), ('cadeira', 'Cadeira Gamer'), ('impressora', 'Impressora'), ('fonte', 'Fonte'), ('gabinete', 'Gabinete'), ('cooler', 'Cooler / Water Cooler'), ('controle', 'Controle / Gamepad'), ('webcam', 'Webcam'), ('roteador', 'Roteador'), ('console', 'Console'), ('cupom', 'Cupom'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
        migrations.RunPython(reclassificar_promos, noop),
    ]
