# Generated by Django 5.0.1 on 2026-08-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_alter_promo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='produto_chave',
            field=models.CharField(blank=True, db_index=True, help_text='Link normalizado (sem preço) que identifica o mesmo produto ao longo do tempo — usado no histórico de preços.', max_length=1000),
        ),
    ]
