# Generated by Django 5.0.1 on 2026-08-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_reclassificar_fans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='categoria',
            field=models.CharField(choices=[('ssd', 'SSD / HD'), ('placa_video', 'Placa de Vídeo'), ('placa_mae', 'Placa-mãe'), ('processador', 'Processador'), ('memoria_ram', 'Memória RAM'), ('kit', 'Kit (Placa + CPU + RAM)'), ('notebook', 'Notebook'), ('monitor', 'Monitor'), ('celular', 'Celular / Smartphone'), ('tv', 'TV'), ('caixa_som', 'Caixa de Som / Soundbar'), ('headset', 'Fone / Headset'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('mousepad', 'Mousepad'), ('cadeira', 'Cadeira Gamer'), ('impressora', 'Impressora'), ('fonte', 'Fonte'), ('gabinete', 'Gabinete'), ('cooler', 'Cooler / Water Cooler'), ('pasta_termica', 'Pasta Térmica'), ('controle', 'Controle / Gamepad'), ('webcam', 'Webcam'), ('microfone', 'Microfone'), ('roteador', 'Roteador'), ('console', 'Console'), ('jogo', 'Jogo'), ('cupom', 'Cupom'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
    ]
