# Generated by Django 5.0.1 on 2026-08-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_reclassificar_cupom_typo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('resumo', models.CharField(blank=True, help_text='Breve descrição exibida na listagem e nas meta tags.', max_length=300)),
                ('conteudo', models.TextField(help_text='Conteúdo em linha única (HTML) ou blocos separados por quebras. Recomenda-se usar tags básicas de HTML (<p>, <h2>, <ul>, <strong>).')),
                ('imagem_url', models.URLField(blank=True, max_length=2000)),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
