# Generated by Django 5.0.1 on 2026-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_artigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de capa do artigo. Enviada em JPG/PNG e convertida automaticamente para WebP.', upload_to='artigos/'),
        ),
    ]
