# Generated by Django 5.0.1 on 2026-08-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0042_remove_artigo_imagem_url_artigo_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='resumo',
        ),
    ]
