# Generated by Django 5.0.1 on 2026-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0045_reclassificar_ventoinhas'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='categoria',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('perifericos', 'Periféricos'), ('celular', 'Celular / Smartphone'), ('console', 'Console / Games'), ('guia', 'Guia de Compra'), ('dicas', 'Dicas & Tutoriais'), ('outros', 'Outros')], db_index=True, default='guia', max_length=30),
        ),
    ]
