# Generated by Django 5.0.1 on 2026-08-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0047_artigo_categoria_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Categoria do artigo (ex.: Celulares, Placas de Vídeo). Você define ao criar.', max_length=50),
        ),
    ]
