# Generated by Django 5.0.1 on 2026-08-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0058_reclassificar_placas_mae'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('whatsapp', models.CharField(db_index=True, help_text='Formato +55DDDNUMERO (gerado automaticamente).', max_length=20)),
                ('keyword', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta do Site',
                'verbose_name_plural': 'Alertas do Site',
                'ordering': ['-created_at'],
            },
        ),
    ]
