# Generated by Django 5.0.1 on 2026-08-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0061_recalcular_chave_celulares'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertasite',
            name='token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Token único para cancelar o alerta pelo link.', max_length=64),
        ),
    ]
