# Generated by Django 5.0.1 on 2026-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0068_reclassificar_titulo_escassez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
