# Generated by Django 5.0.1 on 2026-09-02 13:22

from django.db import migrations, models
from bot.classifier import detectar_categoria
from bot.services import _linha_titulo


def reclassificar(apps, schema_editor):
    """Reclassifica ar condicionados (Ar Condicionado Inverter Hi Wall) que a
    regra antiga marcava como 'Outros'."""
    Promo = apps.get_model('bot', 'Promo')
    for promo in Promo.objects.all().iterator():
        texto = promo.texto_original or promo.titulo
        titulo = _linha_titulo(texto)
        nova = detectar_categoria(texto, titulo=titulo)
        if nova and nova != promo.categoria:
            promo.categoria = nova
            promo.save(update_fields=['categoria'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0094_reclassificar_tvs_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='categoria',
            field=models.CharField(choices=[('ssd', 'SSD / HD'), ('placa_video', 'Placa de Vídeo'), ('placa_mae', 'Placa-mãe'), ('processador', 'Processador'), ('memoria_ram', 'Memória RAM'), ('kit', 'Kit (Placa + CPU + RAM)'), ('notebook', 'Notebook'), ('monitor', 'Monitor'), ('celular', 'Celular / Smartphone'), ('tablet', 'Tablet'), ('tv', 'TV'), ('caixa_som', 'Caixa de Som / Soundbar'), ('headset', 'Fone / Headset'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('mousepad', 'Mousepad'), ('cadeira', 'Cadeira Gamer'), ('impressora', 'Impressora'), ('fonte', 'Fonte'), ('gabinete', 'Gabinete'), ('cooler', 'Cooler / Water Cooler / Fan'), ('pasta_termica', 'Pasta Térmica'), ('controle', 'Controle / Gamepad'), ('webcam', 'Webcam'), ('cabo', 'Cabo / Carregador'), ('microfone', 'Microfone'), ('roteador', 'Roteador'), ('console', 'Console'), ('jogo', 'Jogo'), ('cupom', 'Cupom'), ('ar_condicionado', 'Ar Condicionado'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
        migrations.RunPython(reclassificar, noop),
    ]
