# Generated by Django 5.0.1 on 2026-09-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0106_corrigir_link_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('conteudo', models.TextField(help_text='Conteúdo do aviso (HTML). Recomenda-se usar tags básicas (<p>, <h2>, <ul>, <strong>).')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem do aviso. Enviada em JPG/PNG e convertida automaticamente para WebP.', upload_to='avisos/')),
                ('publicado', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False, help_text='Se marcado, aparece em destaque no topo da página de Promoções.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Quadro de Avisos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
