# Generated by Django 5.0.1 on 2026-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0108_reclassificar_coolers_ryzen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aviso',
            new_name='Evento',
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do evento. Enviada em JPG/PNG e convertida automaticamente para WebP.', upload_to='eventos/'),
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Quadro de Eventos'},
        ),
    ]
