# Generated by Django 5.0.1 on 2026-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0109_rename_aviso_to_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='conteudo',
            field=models.TextField(help_text='Conteúdo do evento (HTML). Recomenda-se usar tags básicas (<p>, <h2>, <ul>, <strong>).'),
        ),
    ]
