# Generated by Django 5.0.1 on 2026-09-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0119_reclassificar_cameras_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='produtos_texto',
            field=models.TextField(blank=True, help_text='Produtos recomendados na barra lateral. Uma linha por produto, no formato: Nome do produto | Loja: https://link | Loja2: https://link2. Ex.: "GameSir Nova Lite | AliExpress: https://s.click.aliexpress.com/x | Shopee: https://s.shopee.com.br/x"'),
        ),
    ]
